# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful_update_interval', models.DurationField(default=datetime.timedelta(0, 21600), help_text=b'How long to wait before updating again after a successful update')),
                ('failed_update_interval', models.DurationField(default=datetime.timedelta(0, 3600), help_text=b'How long to wait before updating again after a failed update')),
            ],
        ),
        migrations.CreateModel(
            name='BackupConfigRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.NullBooleanField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BackupConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default=b'Github', max_length=255)),
                ('slug', models.CharField(help_text=b'e.g. wk8/bitbucketmirrorer', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RepoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default=b'Github', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='repo',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'Can stay blank if your configuration(s) do(es) not require making authenticated calls for this repo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.RepoUser'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='source_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Repo'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='target_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Repo'),
        ),
    ]
